# Generated by Django 4.2.1 on 2023-06-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idEvenement', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=400)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('DatePublication', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('idMoyenTransport', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('NombrePassagers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(default='', max_length=50)),
                ('zoom', models.IntegerField(default=5)),
                ('xcoor', models.FloatField(default=0)),
                ('ycoor', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('idVisiteur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60, null=True)),
                ('Pays', models.CharField(max_length=45)),
                ('NumTel', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteurAuth',
            fields=[
                ('idauth', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60, null=True)),
                ('Pays', models.CharField(max_length=45)),
                ('NumTel', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('idPoint', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('longitude', models.FloatField(default=4)),
                ('latitude', models.FloatField(default=1)),
                ('jours', models.CharField(blank=True, choices=[('dimanche', 'Dimanche'), ('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=100)),
                ('heureOuverture', models.TimeField(default='00:00:00')),
                ('heureFermeture', models.TimeField(default='00:00:00')),
                ('rate', models.FloatField(default=0)),
                ('categorie', models.CharField(default=' ', max_length=50)),
                ('theme', models.CharField(default='', max_length=50)),
                ('regionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
                ('transports', models.ManyToManyField(to='backend.moyentransport')),
            ],
        ),
        migrations.CreateModel(
            name='PiImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('piId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret')),
            ],
        ),
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('eventId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.evenement')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='PiId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('idCommentaire', models.AutoField(primary_key=True, serialize=False)),
                ('Contenu', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('PiId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret')),
                ('visiteurId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.visiteur')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60, null=True)),
                ('NumTel', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=500)),
                ('regionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
            ],
        ),
    ]
